name: Pushing to Dockerhub
run-name: Testing Dockerhub push 
on:
  push:
    branches:
      - master
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build a dev image
        run: | 
          docker build -t zakharsmirnoff/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true zakharsmirnoff/react-test npm test
  push-images:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Logging in to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: Building images
        run: |
          docker build -t zakharsmirnoff/multi-client ./client
          docker build -t zakharsmirnoff/multi-nginx ./nginx
          docker build -t zakharsmirnoff/multi-server ./server
          docker build -t zakharsmirnoff/multi-worker ./worker
      - name: Pushing images
        run: |
          docker push zakharsmirnoff/multi-client
          docker push zakharsmirnoff/multi-nginx
          docker push zakharsmirnoff/multi-server
          docker push zakharsmirnoff/multi-worker
